#!/bin/bash 

source $( dirname $0 )/backup_library

while read dir
do
        absdir=$(readlink -e $dir)
	duplicity $DUPLICITY_ARGS \
		remove-all-but-n-full $NUM_FULL \
		${BACKUP_URI}$absdir $*
done <$BACKUP_SETS
