#!/bin/bash 

source $( dirname $0 )/backup_library

while read dir
do
	absdir=$(readlink -e $dir)
	duplicity $DUPLICITY_ARGS \
  		--full-if-older-than=$FULL_FREQ \
		$absdir ${BACKUP_URI}$absdir $* 
done <$BACKUP_SETS

